# Generated by Django 6.0.5 on 2026-05-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
